### ISSUE TITLE
Storing bind password as an attribute is insecure

### ISSUE THREAD

**Issue by jasonmcintosh** [tas50/chef-sssd_ldap#23]
Should reference a data bag item, vault entry or some other method to get the password.  
['sssd_conf']['ldap_default_authtok']
Storing a plain text password in that attribute is very dangerous for multiple reasons.

**Comment by tas50** [comment]
It could probably be pointed out better, but anything secure should be handled with some sort of wrapper. I don't want to dictate the structure of a data bag since that might not work depending on how the end users has setup their environment.  Letting the end user determine how they pull from data bags and what those data bags are named / structured like gives the most flexibility
